version: '3.7'
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
